title: Computing Education Research Deadlines
description: Countdowns to top Computing Education Research (CER) conference deadlines
author: Joshua Lock

domain: joshuagl.github.io
url: https://joshuagl.github.io/cer-deadlines
baseurl: /cer-deadlines/

github_username: joshuagl
github_repo: cer-deadlines

markdown: kramdown
ga_id:

include: ['_pages']
